trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: src

- script: docker build -t wanwanmedia/fml.web:latest .

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src'
    ArtifactName: FML.Web
   